### ISSUE TITLE
What was your reason for removing DCEL?

### ISSUE THREAD

**Issue by andybak** [Scrawk/CGALDotNetUnity#3]
I'd been keeping an eye on this repo as I've been looking for a half-decent Unity library to replace the halfedge mesh code I borrowed, ported and hacked together myself.

**Comment by Scrawk** [comment]
I was not happy with the design so decided to remove it. 

It was added to provide a way to copy the triangulation and arrangement data structure's in CGAL so you could iterate over them in a C# script. That made it rather specialized and I thought it might get confused for a general DCEL data structure.

**Comment by andybak** [comment]
Thanks. Makes sense.
